// Upload function for photos with prompt to Supabase Storage and database

import { createClient } from "@supabase/supabase-js";

// Setup type definitions for built-in Supabase Runtime APIs
import "@supabase/functions-js/edge-runtime.d.ts";

// Generate image function using Gemini API
async function generateImage(
  photoId: number,
  prompt: string,
  originalImageBuffer: Uint8Array,
  contentType: string,
  supabaseClient: any,
): Promise<string> {
  try {
    console.log(`Generating image for photo ${photoId} with prompt: ${prompt}`);

    // Convert buffer to base64 for API
    const base64Image = btoa(String.fromCharCode(...originalImageBuffer));

    // Call Gemini API for image generation using the new image generation model
    const response = await fetch(
      "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image:generateContent",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-goog-api-key": Deno.env.get("GEMINI_API_KEY")!,
        },
        body: JSON.stringify({
          contents: [{
            parts: [
              {
                text:
                  `Create an image based on this prompt: "${prompt}". Use the provided image as reference for style and composition.`,
              },
              {
                inline_data: {
                  mime_type: contentType,
                  data: base64Image,
                },
              },
            ],
          }],
          generationConfig: {
            imageConfig: {
              aspectRatio: "1:1", // Default to square, can be changed to other ratios
            },
          },
        }),
      },
    );

    if (!response.ok) {
      throw new Error(
        `Gemini API error: ${response.status} ${response.statusText}`,
      );
    }

    const data = await response.json();
    console.log("Gemini response:", JSON.stringify(data, null, 2));

    // Extract the generated image from Gemini's response
    let generatedImageBuffer: Uint8Array;

    if (
      data.candidates && data.candidates[0] && data.candidates[0].content &&
      data.candidates[0].content.parts &&
      data.candidates[0].content.parts.length > 0
    ) {
      // Look for image data in the response parts
      const imagePart = data.candidates[0].content.parts.find((part: any) =>
        part.inline_data && part.inline_data.data
      );

      if (imagePart && imagePart.inline_data && imagePart.inline_data.data) {
        // Gemini returned a generated image
        console.log("Gemini generated an image successfully!");
        generatedImageBuffer = Uint8Array.from(
          atob(imagePart.inline_data.data),
          (c) => c.charCodeAt(0),
        );
      } else {
        // Check if there's text in the response (fallback)
        const textPart = data.candidates[0].content.parts.find((part: any) =>
          part.text
        );
        if (textPart && textPart.text) {
          console.log("Gemini response text:", textPart.text);
        }

        // Fallback to placeholder if no image was generated
        console.log("No image generated by Gemini, using placeholder");
        const placeholderImage =
          "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==";
        generatedImageBuffer = Uint8Array.from(
          atob(placeholderImage.split(",")[1]),
          (c) => c.charCodeAt(0),
        );
      }
    } else {
      console.log("Unexpected Gemini response format, using placeholder");
      const placeholderImage =
        "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==";
      generatedImageBuffer = Uint8Array.from(
        atob(placeholderImage.split(",")[1]),
        (c) => c.charCodeAt(0),
      );
    }

    // Upload generated image to storage
    const timestamp = +new Date();
    const generatedPath = `generated/${photoId}/generated-${timestamp}.png`;

    const { data: upload, error: uploadError } = await supabaseClient.storage
      .from("photos")
      .upload(generatedPath, generatedImageBuffer, {
        contentType: "image/png",
        cacheControl: "3600",
        upsert: false,
      });

    if (uploadError) {
      throw new Error(
        `Failed to upload generated image: ${uploadError.message}`,
      );
    }

    // Get the public URL
    const { data: { publicUrl } } = supabaseClient.storage
      .from("photos")
      .getPublicUrl(upload.path);

    return publicUrl;
  } catch (error) {
    console.error("Error in generateImage:", error);
    throw error;
  }
}

Deno.serve(async (req) => {
  // Only allow POST requests
  if (req.method !== "POST") {
    return new Response("Method not allowed", { status: 405 });
  }

  try {
    const body = await req.json();
    const { image_data, prompt, user_id } = body;

    if (!image_data) {
      return new Response("Missing image data", { status: 400 });
    }

    if (!prompt) {
      return new Response("Missing prompt", { status: 400 });
    }

    // Validate UUID format, if invalid or empty, set to null
    const uuidRegex =
      /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
    const validUserId = user_id && uuidRegex.test(user_id) ? user_id : null;

    // Convert base64 to buffer
    let imageBuffer: Uint8Array;
    let contentType = "image/jpeg"; // default
    let fileExtension = "jpg";

    if (image_data.startsWith("data:image/")) {
      // Handle data URL format: data:image/jpeg;base64,/9j/4AAQ...
      const [header, base64Data] = image_data.split(",");
      const mimeMatch = header.match(/data:image\/([a-zA-Z]*)/);
      if (mimeMatch) {
        contentType = `image/${mimeMatch[1]}`;
        fileExtension = mimeMatch[1];
      }
      imageBuffer = Uint8Array.from(atob(base64Data), (c) => c.charCodeAt(0));
    } else {
      // Handle raw base64 string
      imageBuffer = Uint8Array.from(atob(image_data), (c) => c.charCodeAt(0));
    }

    const supabaseClient = createClient(
      // Supabase API URL - env var exported by default.
      Deno.env.get("SUPABASE_URL")!,
      // Use service role key to bypass RLS
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    );

    // Upload original image to Storage
    const timestamp = +new Date();
    const fileName = `image-${timestamp}.${fileExtension}`;
    const uploadPath = `original/${validUserId || "anonymous"}/${fileName}`;
    const { data: upload, error: uploadError } = await supabaseClient.storage
      .from("photos")
      .upload(uploadPath, imageBuffer, {
        contentType: contentType,
        cacheControl: "3600",
        upsert: false,
      });

    if (uploadError) {
      console.error("Upload error:", uploadError);
      return new Response("Failed to upload the image", { status: 500 });
    }

    // Get the public URL for the uploaded image
    const { data: { publicUrl } } = supabaseClient.storage
      .from("photos")
      .getPublicUrl(upload.path);

    // Insert record to photos table
    const { data: photoData, error: dbError } = await supabaseClient
      .from("photos")
      .insert({
        user_id: validUserId,
        original_image: publicUrl,
        prompt: prompt,
        // generated_image will be null initially, can be updated later
        generated_image: null,
        status: "loading",
      })
      .select()
      .single();

    if (dbError) {
      console.error("Database error:", dbError);
      return new Response("Failed to save photo record", { status: 500 });
    }

    // Generate image asynchronously
    generateImage(
      photoData.id,
      prompt,
      imageBuffer,
      contentType,
      supabaseClient,
    )
      .then((generatedImageUrl) => {
        // Update the database with the generated image
        return supabaseClient
          .from("photos")
          .update({
            generated_image: generatedImageUrl,
            status: "completed",
            updated_at: new Date().toISOString(),
          })
          .eq("id", photoData.id);
      })
      .catch((error) => {
        console.error("Error generating image:", error);
        // Update status to failed if generation fails
        supabaseClient
          .from("photos")
          .update({
            status: "failed",
            updated_at: new Date().toISOString(),
          })
          .eq("id", photoData.id);
      });

    return new Response(
      JSON.stringify({
        success: true,
        photo: photoData,
        message: "Photo uploaded successfully, generation in progress",
      }),
      {
        status: 201,
        headers: { "Content-Type": "application/json" },
      },
    );
  } catch (error) {
    console.error("Error processing request:", error);
    return new Response("Internal server error", { status: 500 });
  }
});
